[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_extra_dirs = 
    middleware
    ; BSP

lib_deps = 
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.0.0
    tzapu/WiFiManager @ ^2.0.17
    arduino-libraries/NTPClient @ ^3.2.1
    ; vshymanskyy/Preferences @ ^2.1.0 ; Only for ESP8266

; Configuration for ESP8266 (Uncomment or switch env to use)
; [env:nodemcuv2]
; platform = espressif8266
; board = nodemcuv2
; framework = arduino
; monitor_speed = 115200
; lib_extra_dirs = 
;     middleware
;     ; BSP
; lib_deps = 
;     marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
;     knolleary/PubSubClient @ ^2.8
;     bblanchon/ArduinoJson @ ^7.0.0
;     tzapu/WiFiManager @ ^2.0.17
;     arduino-libraries/NTPClient @ ^3.2.1
;     vshymanskyy/Preferences @ ^2.1.0 ; Required for ESP8266
